# Generated by Django 4.2.6 on 2023-11-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
